Adding Notifcations
OpenLake/Sampoorna pull request #19
Opened 2022-01-19 20:55 UTC by aastha01chauhan

-This is to send a notification to the user 2 days before the expected date
-Requires some fixing

2022-01-21 18:22 UTC, akshaaatt requested changes
Great job! The work looks promising to me here, though have requested some changes. Let me know if you need any help.

2022-01-21 18:22 UTC, akshaaatt commented on app/build.gradle
> +        minSdk 26
We don't want to do this in any case. Look for alternatives if this is a necessity in the current implementations.

2022-01-21 18:22 UTC, akshaaatt commented on app/src/main/java/org/openlake/sampoorna/presentation/features/periodtracker/Notifications01.kt
> +class Notifications01 : BroadcastReceiver()
The class name here can be better, based on the content of the usage.

2022-01-21 18:22 UTC, akshaaatt commented on app/src/main/res/layout/fragment_tracking.xml
> +        android:textSize="34sp"
We should look to use the @dimen/ implementation here

2022-02-15 18:35 UTC, KShivendu commented
@aastha01chauhan Please do the requested changes. We'll be in a position to merge your code then.

2022-12-25 12:17 UTC, closed without merging